package promax

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"html"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
)

type Result struct{Name string `json:"name"`; Path string `json:"path,omitempty"`; Summary string `json:"summary"`; Data any `json:"data,omitempty"`}
func (r Result) Text() string{b,_:=json.MarshalIndent(r,"","  "); return string(b)}

type HypervisorRole struct{Name string `json:"name"`; Task string `json:"task"`; Tools []string `json:"tools"`; DependsOn []string `json:"depends_on,omitempty"`}
func AgentHypervisor(root, goal string)(Result,error){roles:=[]HypervisorRole{{"architect","Map system and design plan",[]string{"codebase_map","neural_workspace"},nil},{"builder","Implement targeted changes",[]string{"read_file","edit_file","write_file"},[]string{"architect"}},{"tester","Run verification and diagnose failures",[]string{"run_shell","agent_self_test_harness"},[]string{"builder"}},{"ui-agent","Polish terminal UX",[]string{"ui_composer","theme_generator"},[]string{"architect"}},{"docs-agent","Update docs/artifacts",[]string{"readme_designer","docs_portal_generator"},[]string{"builder"}},{"release-agent","Package outputs and timeline",[]string{"artifact_browser","replay_engine"},[]string{"tester","docs-agent"}},{"self-upgrade-agent","Find kernel improvements",[]string{"kernel_upgrade_planner"},[]string{"release-agent"}}}; return Result{"agent_hypervisor","","agent orchestration kernel plan created for: "+goal,roles},nil}

type GraphNode struct{ID string `json:"id"`; Kind string `json:"kind"`; Label string `json:"label"`}
type GraphEdge struct{From string `json:"from"`; To string `json:"to"`; Kind string `json:"kind"`}
type MemoryGraph struct{Nodes []GraphNode `json:"nodes"`; Edges []GraphEdge `json:"edges"`; UpdatedAt time.Time `json:"updated_at"`}
func MemoryGraphTool(root, action, query string)(Result,error){path:=filepath.Join(root,".zed-memory-graph.json"); g:=MemoryGraph{}; if b,err:=os.ReadFile(path);err==nil{_ = json.Unmarshal(b,&g)}; if action=="build"||action==""{g=buildMemoryGraph(root); _=writeJSON(path,g)}; if query!=""{var nodes []GraphNode; for _,n:=range g.Nodes{if strings.Contains(strings.ToLower(n.Label+n.ID+n.Kind),strings.ToLower(query)){nodes=append(nodes,n)}}; return Result{"memory_graph",path,"memory graph query",nodes},nil}; return Result{"memory_graph",path,"memory graph ready",g},nil}
func buildMemoryGraph(root string)MemoryGraph{g:=MemoryGraph{UpdatedAt:time.Now()}; add:=func(id,kind,label string){for _,n:=range g.Nodes{if n.ID==id{return}}; g.Nodes=append(g.Nodes,GraphNode{id,kind,label})}; add("project","root",filepath.Base(root)); filepath.WalkDir(root,func(p string,d os.DirEntry,err error)error{if err!=nil||d.IsDir(){return nil}; rel:=rel(root,p); if strings.HasPrefix(rel,".zed-"){add(rel,"artifact",rel); g.Edges=append(g.Edges,GraphEdge{"project",rel,"has_artifact"})}; if strings.HasSuffix(rel,".go"){add(rel,"file",rel); g.Edges=append(g.Edges,GraphEdge{"project",rel,"contains"})}; return nil}); return g}

type CodebaseMap struct{Packages map[string][]string `json:"packages"`; Imports map[string][]string `json:"imports"`; Tools []string `json:"tools"`; AgentOS []string `json:"agent_os"`}
func CodebaseMapTool(root string)(Result,error){m:=CodebaseMap{Packages:map[string][]string{},Imports:map[string][]string{}}; impRe:=regexp.MustCompile(`"([^"]+)"`); filepath.WalkDir(root,func(p string,d os.DirEntry,err error)error{if err!=nil||d.IsDir()||!strings.HasSuffix(p,".go"){return nil}; dir:=rel(root,filepath.Dir(p)); m.Packages[dir]=append(m.Packages[dir],rel(root,p)); b,_:=os.ReadFile(p); for _,x:=range impRe.FindAllStringSubmatch(string(b),-1){m.Imports[rel(root,p)]=append(m.Imports[rel(root,p)],x[1])}; if strings.Contains(p,"internal/tools"){m.Tools=append(m.Tools,rel(root,p))}; if strings.Contains(p,"agentos")||strings.Contains(p,"promax"){m.AgentOS=append(m.AgentOS,rel(root,p))}; return nil}); return Result{"codebase_map","","codebase map generated",m},nil}

func NeuralWorkspace(root string)(Result,error){status:=run(root,"git status --short"); arts,_:=ArtifactBrowser(root); data:=map[string]any{"time":time.Now(),"root":root,"git_status":status,"artifacts":arts.Data}; path:=filepath.Join(root,".zed-workspace-state.json"); return Result{"neural_workspace",path,"workspace state captured",data},writeJSON(path,data)}

func MergeEngine(root string, apply bool)(Result,error){var files []string; filepath.WalkDir(root,func(p string,d os.DirEntry,err error)error{if err!=nil||d.IsDir(){return nil}; b,_:=os.ReadFile(p); if bytes.Contains(b,[]byte("<<<<<<<")){files=append(files,rel(root,p)); if apply{resolved:=resolveConflictText(string(b)); _=os.WriteFile(p,[]byte(resolved),0644)}}; return nil}); summary:="conflicts detected"; if apply{summary="conflicts auto-resolved by removing markers and keeping combined content"}; return Result{"merge_engine","",summary,map[string]any{"files":files,"applied":apply}},nil}
func resolveConflictText(s string)string{lines:=strings.Split(s,"\n"); var out []string; skip:=false; for _,l:=range lines{if strings.HasPrefix(l,"<<<<<<<")||strings.HasPrefix(l,"=======")||strings.HasPrefix(l,">>>>>>>"){skip=false; continue}; if !skip{out=append(out,l)}}; return strings.Join(out,"\n")}

type PatchItem struct{ID int `json:"id"`; Name string `json:"name"`; Patch string `json:"patch"`; Status string `json:"status"`; CreatedAt time.Time `json:"created_at"`}
type PatchQueueStore struct{NextID int `json:"next_id"`; Items []PatchItem `json:"items"`}
func PatchQueue(root, action, name, patch string, id int)(Result,error){path:=filepath.Join(root,".zed-patch-queue.json"); st:=PatchQueueStore{NextID:1}; if b,err:=os.ReadFile(path);err==nil{_ = json.Unmarshal(b,&st)}; switch action{case "add": it:=PatchItem{st.NextID,name,patch,"queued",time.Now()}; st.NextID++; st.Items=append(st.Items,it); _=writeJSON(path,st); return Result{"patch_queue",path,"patch queued",it},nil; case "approve","apply","rollback": for i:=range st.Items{if st.Items[i].ID==id{st.Items[i].Status=action+"ed"; _=writeJSON(path,st); return Result{"patch_queue",path,"patch updated",st.Items[i]},nil}}}; return Result{"patch_queue",path,"patch queue",st},nil}

type TimelineEvent struct{Time time.Time `json:"time"`; Kind string `json:"kind"`; Text string `json:"text"`; Meta map[string]any `json:"meta,omitempty"`}
func TimelineDB(root, action, kind, text string)(Result,error){path:=filepath.Join(root,".zed-timeline.jsonl"); if action=="append"{e:=TimelineEvent{time.Now(),kind,text,nil}; f,err:=os.OpenFile(path,os.O_CREATE|os.O_APPEND|os.O_WRONLY,0644); if err!=nil{return Result{},err}; defer f.Close(); b,_:=json.Marshal(e); _,err=f.Write(append(b,'\n')); return Result{"timeline_db",path,"event appended",e},err}; evs:=readTimeline(path); return Result{"timeline_db",path,"timeline loaded",evs},nil}
func readTimeline(path string)[]TimelineEvent{f,err:=os.Open(path); if err!=nil{return nil}; defer f.Close(); var evs []TimelineEvent; sc:=bufio.NewScanner(f); for sc.Scan(){var e TimelineEvent; if json.Unmarshal(sc.Bytes(),&e)==nil{evs=append(evs,e)}}; return evs}

func ReplayEngine(root, name string)(Result,error){if name==""{name="replay"}; evs:=readTimeline(filepath.Join(root,".zed-timeline.jsonl")); b:=strings.Builder{}; b.WriteString("<html><body style='background:#0f1115;color:#eee;font-family:monospace'><h1>BITTU Replay</h1>"); for _,e:=range evs{fmt.Fprintf(&b,"<p><b>%s</b> [%s] %s</p>",e.Time.Format(time.RFC3339),html.EscapeString(e.Kind),html.EscapeString(e.Text))}; b.WriteString("</body></html>"); out:=filepath.Join(root,"docs","replays",slug(name)+".html"); _=os.MkdirAll(filepath.Dir(out),0755); return Result{"replay_engine",out,"replay html generated",map[string]int{"events":len(evs)}},os.WriteFile(out,[]byte(b.String()),0644)}

func ArtifactBrowser(root string)(Result,error){var out []string; pats:=[]string{".zed-*","docs/**/*.html","docs/**/*.md","apps/*","web-ui/*","dist/*"}; for _,pat:=range pats{m,_:=filepath.Glob(filepath.Join(root,pat)); out=append(out,m...)}; sort.Strings(out); for i:=range out{out[i]=rel(root,out[i])}; return Result{"artifact_browser","","artifacts listed",out},nil}
func ProjectGeneratorPro(root, name, stack string)(Result,error){if name==""{name="bittu-project"}; if stack==""{stack="go-cli"}; dir:=filepath.Join(root,"projects",slug(name)); _=os.MkdirAll(filepath.Join(dir,"cmd",slug(name)),0755); files:=map[string]string{"README.md":"# "+name+"\n\nStack: "+stack+"\n","go.mod":"module "+slug(name)+"\n\ngo 1.23\n","cmd/"+slug(name)+"/main.go":"package main\n\nimport \"fmt\"\n\nfunc main(){fmt.Println(\""+name+"\")}\n","Makefile":"test:\n\tgo test ./...\nrun:\n\tgo run ./cmd/"+slug(name)+"\n"}; for f,c:=range files{p:=filepath.Join(dir,f); _=os.MkdirAll(filepath.Dir(p),0755); _=os.WriteFile(p,[]byte(c),0644)}; return Result{"project_generator_pro",dir,"project generated",files},nil}
func PreviewServer(root,path string)(Result,error){target:=resolve(root,path); cmd:="python3 -m http.server 8080 --directory "+quote(filepath.Dir(target)); return Result{"preview_server",target,"preview command generated",map[string]string{"command":cmd,"url":"http://localhost:8080/"+filepath.Base(target)}},nil}
func WebUIExporter(root string)(Result,error){arts,_:=ArtifactBrowser(root); outdir:=filepath.Join(root,"web-ui"); _=os.MkdirAll(outdir,0755); b,_:=json.Marshal(arts.Data); htmlText:="<html><body><h1>BITTU CHAUHAN Web UI</h1><pre>"+html.EscapeString(string(b))+"</pre></body></html>"; return Result{"web_ui_exporter",outdir,"web UI exported",nil},os.WriteFile(filepath.Join(outdir,"index.html"),[]byte(htmlText),0644)}
func PluginBuilder(root,name,desc string)(Result,error){if name==""{name="custom_tool"}; fn:=slug(name); code:="package tools\n\nimport (\n \"context\"\n)\n\ntype "+camel(fn)+" struct{}\nfunc (t *"+camel(fn)+") Name() string { return \""+fn+"\" }\nfunc (t *"+camel(fn)+") Description() string { return \""+desc+"\" }\nfunc (t *"+camel(fn)+") RequiresApproval() bool { return false }\nfunc (t *"+camel(fn)+") Schema() map[string]any { return map[string]any{\"type\":\"object\",\"properties\":map[string]any{}} }\nfunc (t *"+camel(fn)+") Execute(_ context.Context,args string)(string,error){ return \"ok\", nil }\n"; out:=filepath.Join(root,"internal","tools",fn+".go"); return Result{"plugin_builder",out,"plugin skeleton generated",nil},os.WriteFile(out,[]byte(code),0644)}
func AgentSelfTestHarness(root string)(Result,error){test:="package tools\n\nimport \"testing\"\n\nfunc TestParseArgsEmpty(t *testing.T){ var v struct{}; if parseArgs(\"{}\", &v) != nil {} }\n"; out:=filepath.Join(root,"internal","tools","agent_self_test_harness_test.go"); return Result{"agent_self_test_harness",out,"self-test harness generated",nil},os.WriteFile(out,[]byte(test),0644)}
func BenchmarkLab(root string)(Result,error){start:=time.Now(); _=run(root,"git status --short"); gitDur:=time.Since(start); start=time.Now(); _,_=os.ReadDir(root); readDur:=time.Since(start); data:=map[string]string{"git_status":gitDur.String(),"read_dir":readDur.String()}; out:=filepath.Join(root,".zed-benchmark-lab.json"); return Result{"benchmark_lab",out,"benchmark lab complete",data},writeJSON(out,data)}
func ToolReliabilityScore(root string)(Result,error){evs:=readTimeline(filepath.Join(root,".zed-timeline.jsonl")); counts:=map[string]int{}; for _,e:=range evs{counts[e.Kind]++}; return Result{"tool_reliability_score","","reliability score from timeline",counts},nil}
func ToolAutoRepair(root, input string)(Result,error){fixed:=strings.TrimSpace(input); fixed=strings.NewReplacer("“","\"","”","\"","`","").Replace(fixed); if !strings.HasPrefix(fixed,"{"){if i:=strings.Index(fixed,"{");i>=0{if j:=strings.LastIndex(fixed,"}");j>i{fixed=fixed[i:j+1]}}}; return Result{"tool_auto_repair","","repaired candidate arguments",map[string]string{"input":input,"repaired":fixed}},nil}

type Job struct{ID int `json:"id"`; Command string `json:"command"`; PID int `json:"pid"`; Log string `json:"log"`; StartedAt time.Time `json:"started_at"`; Status string `json:"status"`}
type JobStore struct{NextID int `json:"next_id"`; Jobs []Job `json:"jobs"`}
func JobManager(root, action, command string, id int)(Result,error){path:=filepath.Join(root,".zed-jobs.json"); st:=JobStore{NextID:1}; if b,err:=os.ReadFile(path);err==nil{_ = json.Unmarshal(b,&st)}; if action=="start"{log:=filepath.Join(root,".zed-job-"+strconv.Itoa(st.NextID)+".log"); f,_:=os.Create(log); cmd:=exec.Command("sh","-c",command); cmd.Dir=root; cmd.Stdout=f; cmd.Stderr=f; if err:=cmd.Start();err!=nil{return Result{},err}; j:=Job{st.NextID,command,cmd.Process.Pid,log,time.Now(),"running"}; st.NextID++; st.Jobs=append(st.Jobs,j); _=writeJSON(path,st); return Result{"job_manager",path,"job started",j},nil}; if action=="stop"{for i:=range st.Jobs{if st.Jobs[i].ID==id{_ = exec.Command("kill",strconv.Itoa(st.Jobs[i].PID)).Run(); st.Jobs[i].Status="stopped"; _=writeJSON(path,st); return Result{"job_manager",path,"job stopped",st.Jobs[i]},nil}}}; return Result{"job_manager",path,"jobs listed",st},nil}
func WorkspaceSync(root,dest string)(Result,error){if dest==""{dest=filepath.Join(root,".zed-sync")}; _=os.MkdirAll(dest,0755); copied:=[]string{}; for _,pat:=range []string{".zed-prompts",".zed-skills",".zed-macros",".zed-workflows.json",".zed-knowledge",".zed-missions.json"}{src:=filepath.Join(root,pat); if _,err:=os.Stat(src);err==nil{_ = copyPath(src,filepath.Join(dest,pat)); copied=append(copied,pat)}}; return Result{"workspace_sync",dest,"workspace assets synced",copied},nil}
func KernelUpgradePlanner(root string)(Result,error){mapRes,_:=CodebaseMapTool(root); plan:="# Kernel Upgrade Plan\n\n- Split large tool files\n- Add tests for promax tools\n- Add persistent timeline hooks in registry\n- Add UI tabs for Agent OS Pro Max\n\n```json\n"+mapRes.Text()+"\n```\n"; out:=filepath.Join(root,"docs","kernel-upgrade-plan.md"); _=os.MkdirAll(filepath.Dir(out),0755); return Result{"kernel_upgrade_planner",out,"kernel upgrade plan written",nil},os.WriteFile(out,[]byte(plan),0644)}

func rel(root,p string)string{r,err:=filepath.Rel(root,p); if err!=nil{return filepath.ToSlash(p)}; return filepath.ToSlash(r)}
func resolve(root,p string)string{if p==""{return root}; if filepath.IsAbs(p){return p}; return filepath.Join(root,p)}
func writeJSON(path string,v any)error{_ = os.MkdirAll(filepath.Dir(path),0755); b,_:=json.MarshalIndent(v,"","  "); return os.WriteFile(path,b,0644)}
func run(root,command string)string{cmd:=exec.Command("sh","-c",command); cmd.Dir=root; var b bytes.Buffer; cmd.Stdout=&b; cmd.Stderr=&b; _=cmd.Run(); return b.String()}
func quote(s string)string{return "'"+strings.ReplaceAll(s,"'","'\\''")+"'"}
func slug(s string)string{s=strings.ToLower(s); s=regexp.MustCompile(`[^a-z0-9]+`).ReplaceAllString(s,"-"); return strings.Trim(s,"-")}
func camel(s string)string{parts:=strings.FieldsFunc(s,func(r rune)bool{return r=='-'||r=='_'}); for i,p:=range parts{if p!=""{parts[i]=strings.ToUpper(p[:1])+p[1:]}}; return strings.Join(parts,"")}
func copyPath(src,dst string)error{info,err:=os.Stat(src); if err!=nil{return err}; if info.IsDir(){return filepath.WalkDir(src,func(p string,d os.DirEntry,err error)error{if err!=nil{return err}; r,_:=filepath.Rel(src,p); target:=filepath.Join(dst,r); if d.IsDir(){return os.MkdirAll(target,0755)}; return copyFile(p,target)})}; return copyFile(src,dst)}
func copyFile(src,dst string)error{_ = os.MkdirAll(filepath.Dir(dst),0755); in,err:=os.Open(src); if err!=nil{return err}; defer in.Close(); out,err:=os.Create(dst); if err!=nil{return err}; defer out.Close(); _,err=io.Copy(out,in); return err}
