package agentos

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"image"
	_ "image/gif"
	_ "image/jpeg"
	_ "image/png"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
)

type Result struct { Name string `json:"name"`; Path string `json:"path,omitempty"`; Summary string `json:"summary"`; Data any `json:"data,omitempty"` }
func (r Result) Text() string { b,_:=json.MarshalIndent(r,"","  "); return string(b) }

type VisionSpec struct { File string `json:"file"`; Size int64 `json:"size"`; SHA256 string `json:"sha256"`; Width int `json:"width,omitempty"`; Height int `json:"height,omitempty"`; Theme string `json:"theme"`; Layout []string `json:"layout"`; Components []string `json:"components"`; SuggestedFiles []string `json:"suggested_files"`; UIPrompt string `json:"ui_prompt"` }
func VisionUIBuilder(root, path string) (Result,error){ p:=resolve(root,path); b,err:=os.ReadFile(p); if err!=nil{return Result{},err}; sum:=sha256.Sum256(b); spec:=VisionSpec{File:filepath.ToSlash(p),Size:int64(len(b)),SHA256:hex.EncodeToString(sum[:]),Theme:"dark terminal / enterprise agent UI",Layout:[]string{"top chrome bar","center brand/logo","conversation panel","large prompt box","footer shortcut hints"},Components:[]string{"brand header","center logo","auth/setup panel","prompt input","status footer"},SuggestedFiles:[]string{"internal/tui/model.go","internal/tui/theme.go","internal/tui/enterprise_views.go"}}; if cfg,_,err:=image.DecodeConfig(bytes.NewReader(b)); err==nil{spec.Width=cfg.Width; spec.Height=cfg.Height}; spec.UIPrompt=fmt.Sprintf("Create a dark enterprise terminal UI inspired by %s with BITTU CHAUHAN branding, centered logo, prompt box, footer shortcuts, and premium status chrome.", filepath.Base(path)); return Result{Name:"enterprise_vision_ui_builder",Path:p,Summary:"image analyzed into UI implementation spec",Data:spec},nil }

type PromptPack struct{Name string `json:"name"`; Version string `json:"version"`; Description string `json:"description"`; Variables []string `json:"variables"`; Template string `json:"template"`}
func PromptOS(root, action, name string, vars map[string]string)(Result,error){ dir:=filepath.Join(root,".zed-prompts"); _=os.MkdirAll(filepath.Join(dir,"packs"),0755); _=os.MkdirAll(filepath.Join(dir,"roles"),0755); _=os.MkdirAll(filepath.Join(dir,"workflows"),0755); if action=="init"||action==""{pack:=PromptPack{Name:"enterprise-feature",Version:"1.0",Description:"Build an enterprise feature with tests and evidence",Variables:[]string{"goal","constraints"},Template:"Goal: {{goal}}\nConstraints: {{constraints}}\nPlan, implement, verify, produce evidence."}; writeJSON(filepath.Join(dir,"packs","enterprise-feature.json"),pack); return Result{Name:"prompt_os",Path:dir,Summary:"prompt OS initialized",Data:pack},nil}; if action=="render"{buf,err:=os.ReadFile(filepath.Join(dir,"packs",name+".json")); if err!=nil{return Result{},err}; var p PromptPack; _=json.Unmarshal(buf,&p); out:=p.Template; for k,v:=range vars{out=strings.ReplaceAll(out,"{{"+k+"}}",v)}; return Result{Name:"prompt_os",Summary:"prompt rendered",Data:map[string]string{"prompt":out}},nil}; entries,_:=filepath.Glob(filepath.Join(dir,"packs","*.json")); return Result{Name:"prompt_os",Path:dir,Summary:"prompt packs listed",Data:entries},nil }

type Role struct{Name string `json:"name"`; Goal string `json:"goal"`; Output string `json:"output"`; Tools []string `json:"tools"`}
func RoleStudio(root, task string)(Result,error){ roles:=[]Role{{"Architect","Design architecture and boundaries","architecture plan",[]string{"enterprise_architecture_brain"}},{"Builder","Implement code changes","patch",[]string{"read_file","edit_file","write_file"}},{"Tester","Verify behavior","test report",[]string{"run_shell","enterprise_build_doctor"}},{"UI Designer","Polish terminal UI","UI spec",[]string{"ui_composer","theme_generator"}},{"Docs","Update docs and tutorials","docs",[]string{"knowledge_pack_builder","tutorial_builder"}}}; return Result{Name:"agent_role_studio",Summary:"multi-agent role split created for: "+task,Data:roles},nil }

type Skill struct{Name string `json:"name"`; Description string `json:"description"`; Prompt string `json:"prompt"`; Verification string `json:"verification"`; OutputFormat string `json:"output_format"`; Tools []string `json:"tools"`}
func SkillMarketplace(root, action string, skill Skill)(Result,error){ dir:=filepath.Join(root,".zed-skills"); _=os.MkdirAll(dir,0755); if action=="install"||action=="init"{ if skill.Name==""{skill=Skill{Name:"terminal-theme",Description:"Create premium terminal UI themes",Prompt:"Generate cohesive Lipgloss styles",Verification:"go test ./...",OutputFormat:"go files",Tools:[]string{"theme_generator","ui_composer"}}}; path:=filepath.Join(dir,skill.Name+".skill.json"); return Result{Name:"skill_marketplace",Path:path,Summary:"skill installed",Data:skill},writeJSON(path,skill)}; files,_:=filepath.Glob(filepath.Join(dir,"*.skill.json")); return Result{Name:"skill_marketplace",Path:dir,Summary:"skills listed",Data:files},nil }

type UISpec struct{Screen string `json:"screen"`; Components []map[string]any `json:"components"`}
func UIComposer(root string, spec UISpec)(Result,error){ if spec.Screen==""{spec=UISpec{Screen:"auth",Components:[]map[string]any{{"type":"logo","text":"BITTU CHAUHAN"},{"type":"input","placeholder":"Paste token here..."},{"type":"footer","keys":[]string{"enter submit","ctrl+q quit"}}}}}; var b strings.Builder; fmt.Fprintf(&b,"package generated\n\n// Generated UI spec for %s. Copy into Bubble Tea/Lipgloss screen code.\n",spec.Screen); b.WriteString("var Components = []string{\n"); for _,c:=range spec.Components{fmt.Fprintf(&b,"\t%q,\n",fmt.Sprint(c))}; b.WriteString("}\n"); out:=filepath.Join(root,"generated_ui_"+slug(spec.Screen)+".go"); return Result{Name:"ui_composer",Path:out,Summary:"Go UI component spec generated",Data:spec},os.WriteFile(out,[]byte(b.String()),0644) }

type Macro struct{Name string `json:"name"`; Commands []string `json:"commands"`; UpdatedAt time.Time `json:"updated_at"`}
func MacroRecorder(root, action, name, command string)(Result,error){ dir:=filepath.Join(root,".zed-macros"); _=os.MkdirAll(dir,0755); path:=filepath.Join(dir,name+".json"); if action=="add"{var m Macro; if buf,err:=os.ReadFile(path);err==nil{_ = json.Unmarshal(buf,&m)}; m.Name=name; m.Commands=append(m.Commands,command); m.UpdatedAt=time.Now(); return Result{Name:"macro_recorder",Path:path,Summary:"macro command added",Data:m},writeJSON(path,m)}; files,_:=filepath.Glob(filepath.Join(dir,"*.json")); return Result{Name:"macro_recorder",Path:dir,Summary:"macros listed",Data:files},nil }

type Workflow struct{On, If string `json:"on"`; Do []string `json:"do"`}
func WorkflowEngine(root, action, eventPath string, run bool)(Result,error){ path:=filepath.Join(root,".zed-workflows.json"); if action=="init"||action==""{wf:=[]Workflow{{On:"file_change",If:"path matches internal/tui/*.go",Do:[]string{"go test ./...","enterprise_patch_bundle"}}}; return Result{Name:"workflow_engine",Path:path,Summary:"workflow file initialized",Data:wf},writeJSON(path,wf)}; var wfs []Workflow; buf,err:=os.ReadFile(path); if err!=nil{return Result{},err}; _=json.Unmarshal(buf,&wfs); matched:=[]Workflow{}; for _,w:=range wfs{if workflowMatches(w,eventPath){matched=append(matched,w)}}; outputs:=[]string{}; if run{for _,w:=range matched{for _,c:=range w.Do{outputs=append(outputs,runCommand(root,c))}}}; return Result{Name:"workflow_engine",Path:path,Summary:"workflows evaluated",Data:map[string]any{"matched":matched,"outputs":outputs}},nil }

func DesktopView(root string)(Result,error){ tabs:=[]string{"chat","plan","diff","logs","prompts","agents","skills","workflows"}; return Result{Name:"agent_desktop",Summary:"terminal desktop layout generated",Data:map[string]any{"tabs":tabs,"panels":[]string{"left navigator","center workspace","right inspector","bottom prompt"}}},nil }
func CodeMovie(root, title string)(Result,error){ if title==""{title="code-movie"}; diff:=runCommand(root,"git diff HEAD"); journal,_:=os.ReadFile(filepath.Join(root,".zed-work-journal.jsonl")); html:="<html><body style='background:#0f1115;color:#eee;font-family:monospace'><h1>"+title+"</h1><h2>Diff</h2><pre>"+escapeHTML(diff)+"</pre><h2>Journal</h2><pre>"+escapeHTML(string(journal))+"</pre></body></html>"; out:=filepath.Join(root,"docs","code-movies",slug(title)+".html"); _=os.MkdirAll(filepath.Dir(out),0755); return Result{Name:"code_movie",Path:out,Summary:"code movie HTML generated"},os.WriteFile(out,[]byte(html),0644) }
func AnimationEngine(kind string)(Result,error){ frames:=[]string{"◐ BITTU CHAUHAN","◓ BITTU CHAUHAN","◑ BITTU CHAUHAN","◒ BITTU CHAUHAN"}; if kind=="progress"{frames=[]string{"[░░░░░]","[██░░░]","[████░]","[█████]"}}; return Result{Name:"terminal_animation_engine",Summary:"animation frames generated",Data:frames},nil }
func AppBuilder(root, idea string)(Result,error){ name:=slug(idea); if name==""{name="bittu-app"}; dir:=filepath.Join(root,"apps",name); _=os.MkdirAll(dir,0755); files:=map[string]string{"README.md":"# "+idea+"\n\nGenerated app scaffold.\n","main.go":"package main\n\nimport \"fmt\"\n\nfunc main(){fmt.Println(\""+idea+"\")}\n","main_test.go":"package main\n\nimport \"testing\"\n\nfunc TestApp(t *testing.T){}\n","run.sh":"#!/usr/bin/env bash\ngo run .\n"}; for f,c:=range files{_ = os.WriteFile(filepath.Join(dir,f),[]byte(c),0644)}; return Result{Name:"autonomous_app_builder",Path:dir,Summary:"app scaffold generated",Data:files},nil }
func BlueprintEngine(root, dsl string)(Result,error){ screens:=regexp.MustCompile(`screen\s+(\w+)`).FindAllStringSubmatch(dsl,-1); workflows:=regexp.MustCompile(`workflow\s+(\w+)`).FindAllStringSubmatch(dsl,-1); data:=map[string]any{"screens":screens,"workflows":workflows,"source":dsl}; out:=filepath.Join(root,".zed-blueprint.json"); return Result{Name:"blueprint_engine",Path:out,Summary:"blueprint parsed",Data:data},writeJSON(out,data) }
func ThemeGenerator(root, prompt string)(Result,error){ palette:=map[string]string{"background":"#0f1115","panel":"#121417","accent":"#7CFF9B","text":"#ECEFF4","muted":"#777D8B"}; if strings.Contains(strings.ToLower(prompt),"cyber"){palette["accent"]="#00F5FF"}; if strings.Contains(strings.ToLower(prompt),"matrix"){palette["accent"]="#00FF66"}; out:=filepath.Join(root,".zed-theme-"+slug(prompt)+".json"); return Result{Name:"theme_generator",Path:out,Summary:"theme palette generated",Data:palette},writeJSON(out,palette) }
func PersonaEngine(root, persona string)(Result,error){ personas:=map[string]string{"designer":"You are a premium terminal UI designer.","staff-engineer":"You are a pragmatic staff engineer.","reviewer":"You are a strict code reviewer.","devops":"You are a production DevOps engineer."}; if persona==""{return Result{Name:"persona_engine",Summary:"personas listed",Data:personas},nil}; out:=filepath.Join(root,".zed-persona.json"); return Result{Name:"persona_engine",Path:out,Summary:"persona selected",Data:map[string]string{"persona":persona,"prompt":personas[persona]}},writeJSON(out,map[string]string{"persona":persona,"prompt":personas[persona]}) }
func KnowledgePackBuilder(root string)(Result,error){ dir:=filepath.Join(root,".zed-knowledge"); _=os.MkdirAll(dir,0755); files:=map[string]string{"architecture.md":"# Architecture\n\nGenerated from project structure.\n","commands.md":"# Commands\n\n- go test ./...\n- ./zed --demo\n","conventions.md":"# Conventions\n\nFollow existing Go style and enterprise gates.\n","glossary.md":"# Glossary\n\nBITTU CHAUHAN: Enterprise agent CLI.\n","onboarding.md":"# Onboarding\n\nRun setup, then dashboard, then plan mode.\n"}; for f,c:=range files{_ = os.WriteFile(filepath.Join(dir,f),[]byte(c),0644)}; return Result{Name:"knowledge_pack_builder",Path:dir,Summary:"local project knowledge pack generated",Data:files},nil }
type LearningEvent struct{Time time.Time `json:"time"`; Kind string `json:"kind"`; Text string `json:"text"`}
func LearningSystem(root, kind, text string)(Result,error){ path:=filepath.Join(root,".zed-learning.json"); var evs []LearningEvent; if buf,err:=os.ReadFile(path);err==nil{_ = json.Unmarshal(buf,&evs)}; if kind!=""{evs=append(evs,LearningEvent{Time:time.Now(),Kind:kind,Text:text}); _=writeJSON(path,evs)}; return Result{Name:"learning_system",Path:path,Summary:"learning events",Data:evs},nil }
func TutorialBuilder(root string)(Result,error){ out:=filepath.Join(root,"docs","tutorials","getting-started.md"); _=os.MkdirAll(filepath.Dir(out),0755); c:="# Getting Started\n\n1. Build: `go build -o zed ./cmd/zed`\n2. Demo: `./zed --demo`\n3. Plan: `/plan <goal>`\n4. Verify: `./zed --enterprise-policy-gate`\n"; return Result{Name:"tutorial_builder",Path:out,Summary:"interactive tutorial generated"},os.WriteFile(out,[]byte(c),0644) }
func ReadmeDesigner(root string)(Result,error){ out:=filepath.Join(root,"README_DESIGNED.md"); c:="# BITTU CHAUHAN Enterprise Agent OS\n\n> Premium autonomous engineering terminal.\n\n## Features\n\n- Plan mode\n- Agent OS tools\n- Enterprise evidence\n- Beautiful TUI\n\n## Quickstart\n\n```bash\ngo build -o zed ./cmd/zed\n./zed --demo\n```\n"; return Result{Name:"readme_designer",Path:out,Summary:"professional README generated"},os.WriteFile(out,[]byte(c),0644) }
func VoiceCommandMode(text string)(Result,error){ grammar:=map[string]string{"plan":"/plan "+text,"dashboard":"/dashboard","review":"/review","demo":"--demo"}; return Result{Name:"voice_command_mode",Summary:"voice-ready command grammar parsed",Data:grammar},nil }
func SelfUpgradeKernel(root string)(Result,error){ var goFiles, toolFiles int; _=filepath.WalkDir(filepath.Join(root,"internal"),func(p string,d fs.DirEntry,err error)error{if err==nil&&!d.IsDir()&&strings.HasSuffix(p,".go"){goFiles++; if strings.Contains(p,"tools"){toolFiles++}}; return nil}); rec:=[]string{"Add focused tests for new Agent OS tools","Split large TUI files into screens","Add theme variants beyond dark enterprise","Add tool schema examples"}; return Result{Name:"self_upgrade_kernel",Summary:"self-upgrade recommendations generated",Data:map[string]any{"go_files":goFiles,"tool_files":toolFiles,"recommendations":rec}},nil }

func resolve(root,p string)string{if p==""{return root}; if filepath.IsAbs(p){return p}; return filepath.Join(root,p)}
func writeJSON(path string,v any)error{_ = os.MkdirAll(filepath.Dir(path),0755); b,_:=json.MarshalIndent(v,"","  "); return os.WriteFile(path,b,0644)}
func slug(s string)string{s=strings.ToLower(s); s=regexp.MustCompile(`[^a-z0-9]+`).ReplaceAllString(s,"-"); return strings.Trim(s,"-")}
func runCommand(root, command string)string{cmd:=exec.Command("sh","-c",command); cmd.Dir=root; var b bytes.Buffer; cmd.Stdout=&b; cmd.Stderr=&b; _=cmd.Run(); return b.String()}
func workflowMatches(w Workflow,p string)bool{if w.On!="file_change"{return false}; if !strings.Contains(w.If,"path matches"){return true}; pat:=strings.TrimSpace(strings.TrimPrefix(w.If,"path matches")); ok,_:=filepath.Match(pat,filepath.ToSlash(p)); return ok}
func escapeHTML(s string)string{s=strings.ReplaceAll(s,"&","&amp;"); s=strings.ReplaceAll(s,"<","&lt;"); s=strings.ReplaceAll(s,">","&gt;"); return s}
func ListArtifacts(root string) ([]string,error){var out []string; for _,pat:=range []string{".zed-*","docs/code-movies/*.html","docs/tutorials/*.md","apps/*"}{m,_:=filepath.Glob(filepath.Join(root,pat)); out=append(out,m...)}; sort.Strings(out); return out,nil }
